package exercicioEnumeracao;

public class EnunciadoDoExercicio {
	//LER OS DADOS DE UM TRABALHADOR COM N CONTRATOS(N FORNECIDO PELO USUARIO). DEPOIS SOLICITAR
	//DO USUARIO UM MÊS E MOSTRAR QUAL FOI O SALARIO DO FUNCIONARIO NESSE MES 

}
